#include "r_cg_userdefine.h"

extern char RX_ACK_Frame,ACK,ERROR_OCCURED,RX_SMS_CMD,RX_CMD_SMS[10],t,SMS_FAIL_COUNT,SMS_FAIL,NETWORK_NAME_RX,BATTERY_MEASUREMENT;
extern char INITIAL_MESSAGE,P_LAT_DM_RX,FILE_CLOSE_ATTEMPT;
extern char GSM_REG,GPRS_REG,SS_DATA_RX,GET_SS,dBm,SMS_MOBILE_NO[55];
extern char GPRS_CONNECTED,GSM_STRENGTH,INTERNET_CONNECTED,DISCONNECT,LOW_BATTERY_ALERT,HTTP_CONNECT_COUNT,VEICHLE_NUMBER[15],NW_NAME_RX,IMEI[16];
extern unsigned int RESTART,FOR_1,FOR_3,Address_1,NW_REGN_COUNT,FLASH_MEMORY,GPRS_REG_COUNT,MAIN_BATTERY_VOLTAGE,ADC_BUFFER,BACKUP_BATTERY_VOLTAGE,GPRS_REG_ROAMING,GSM_REG_ROAMING,T_SPEED,FILTER,DATA_HEADER,TEMP_VERSION;
extern unsigned int t_count,WRITE_ADDRESS,DATA,WATCH_DOG_KILL,WRITE_ADDRESS,TEMPS,WRITE_ADDRESS_MSB,WRITE_ADDRESS_LSB,BYTE;
extern char LOG_DM[10],LAT_DM[10],TIME[10],GPS_BUSY,SPEED[4],SPEED_DATA_RX[10],WATCH_DOG,FIRM_DATA[150],FILE[150];
extern char GPS_DIRECTION_DATA_VALID,IGNITION,PANIC_ALERT,PANIC_ALERT_PACKET,IGNITION_ON_PACKET,IGNITION_OFF_PACKET,POWER_SOURCE_PACKET,LOW_BATTERY_ALERT_PACKET;
extern char HOURS_MSB,HOURS_LSB,MIN_MSB,MIN_LSB,LON_DIRECTION,LAT_DIRECTION,LAT_DM_RX[10],LOG_DM_RX[10],COG[6],GPGA_DATA[10],ALTITUDE[8],HDOP[5],NO_OF_SAT,NAVIGATION_ACK,NAVIGATION_RX,GPS_RESTART;

extern char Array_0[10],i,SMS,NETWORK_FAILURE,HTTP_PRINT,SPEED_DATA[10];
extern char NETWORK_NAME[8],SS_DATA_RX;
extern char GSM_NW_REG[8],GPRS_NW_REG[9],OK_ACK[2];
//extern char GET_IN_SMS[4],CONNECT_ACK[7],SIGNAL_STRENGTH_ACK[5],NW_DIS_CONNECT[9];

extern char CPIN;
extern char P_LAT_DM[10],P_TIME[10],P_SEND_TIME[10],P_LOG_DM[10],P_SEND_LOG_DM[10],P_SEND_LAT_DM[10],FTP_ADDRESS[8],FTP_CONNECT_COUNT;
extern char FILE_ADDR,V_NO_LEN;
extern unsigned int CHECKSUM_BYTE,MN,VERSION_TEMP,FRM_VERSION,CURRENT_FRM_VERSION,HEX;
extern _Bool FIRMWARE_UPDATE,IGNITION_CONTROL_STATE,POWER_SOURCE,SYSTEM_READY,MAIN_BAT_STATUS;
extern _Bool HTTP_DOWNLOAD_ACK,FTP_ACK,FTP_DOWNLOAD_ACK,FIRMWARE_DOWNLOADED,FILE_ACK,FILE_DOWNLOAD,FLAG,STOP_FILE_READING,IMEI_RX,IMEI_ACK_RX;
extern _Bool GPS_STANDBY,WATCH_DOG_FORCE_KILL;
//extern unsigned int TEMP_3;
extern int AD;
extern char p1,p2,p3,p4;


void ADDRESS_INC(void)
{
MS_TIMER(1);
WRITE_ADDRESS++;
WRITE_ADDRESS_LSB=WRITE_ADDRESS%256;NOP();
WRITE_ADDRESS_MSB=WRITE_ADDRESS/256;NOP();
}
void EEPROM_FILE_WRITE(void)
{
	  if(DATA_HEADER==0xFF00)
	  {
		  NOP();
		  DATA_HEADER=0x00;
	  }
	  
	  DATA_HEADER=DATA_HEADER+0xFF;
	  
	  CHECKSUM_BYTE=0;
	  FIRM_DATA[1]=0x01;
	  FIRM_DATA[2]=((DATA_HEADER&0XFF00)>>8);
	  FIRM_DATA[3]=((DATA_HEADER&0X00FF));
	  MN=4;
	  for(FOR_1=1;FOR_1<=128;FOR_1++)
	  {
          CHECKSUM_BYTE=FILE[FOR_1]+CHECKSUM_BYTE;
          if(CHECKSUM_BYTE>=0x100){CHECKSUM_BYTE=CHECKSUM_BYTE-0x100;}
	  FIRM_DATA[MN]=FILE[FOR_1];
	  MN++;
	  }
	  FIRM_DATA[132]=CHECKSUM_BYTE;
	  BYTE=1;
	  
NOP();	  
	        while(BYTE<133)
	  	{
		WRITE_ADDRESS_LSB=WRITE_ADDRESS%256;NOP();
		WRITE_ADDRESS_MSB=WRITE_ADDRESS/256;NOP();
		MS_TIMER(5);
		//i2c_PAGE_WRITE(0xA0,WRITE_ADDRESS_MSB,WRITE_ADDRESS_LSB);
		MS_TIMER(5);
		}
	  
	  
	  
}

void FILE_CLOSE(void)
{
RESTART_FILE_CLOSE:
R_UART2_SEND("AT+QFCLOSE=");
for(FOR_1=1;FOR_1<=6;FOR_1++){R_UART2_SEND_User(FTP_ADDRESS[FOR_1]);NOP();}
R_UART2_SEND("\r\n");
ACK_RX(500,2,1,1);
     if(FILE_CLOSE_ATTEMPT>=5){RESTART=OFF;goto SKIP;}
else if(RESTART==ON){FILE_CLOSE_ATTEMPT++;RESTART=OFF;goto RESTART_FILE_CLOSE;}
SKIP:
FILE_CLOSE_ATTEMPT=CLR;
NOP();
}




//void EEPROM_FILE_READ(void)
//{
//WRITE_ADDRESS=WRITE_ADDRESS_MSB=WRITE_ADDRESS_LSB=0;
//R_UART2_SEND("\r\n\r\nEEPROM READING\r\n");
//for(FOR_1=1;FOR_1<=2600;FOR_1++)
//{
////AD=i2c_readn(0xA0,WRITE_ADDRESS_MSB,WRITE_ADDRESS_LSB);MS_TIMER(1);
//ADDRESS_INC();

//	  p1=AD/100;
//	  p2=AD%100;
//	  p3=p2/10;
//	  p4=p2%10;
//	  R_UART2_SEND_User(Array_0[p1]);
//	  R_UART2_SEND_User(Array_0[p3]);
//	  R_UART2_SEND_User(Array_0[p4]);
//	  R_UART2_SEND(" ");
//	  if(WRITE_ADDRESS%133==0){R_UART2_SEND("\r\n\r\n");}
//	  }
//}
void FIRMWARE_DOWNLOAD_FROM_M95(void)
{
	
restart_ftp:	

	 if(FTP_CONNECT_COUNT>=7){FTP_CONNECT_COUNT=0;goto SKIP;}
	 R_UART2_SEND("AT+QFOPEN=\"RAM:1.TXT\",0\r\n");ACK_RX(500,9,100,10);
	       if(DISCONNECT==ON){goto SKIP;}
          else if(RESTART==ON){FTP_CONNECT_COUNT++;RESTART=OFF;goto restart_ftp;}
 	  ACK=0;
	  

          Address_1=0;
	  DATA_HEADER=0xFF;FILTER=1;
	  WRITE_ADDRESS_MSB=WRITE_ADDRESS_LSB=WRITE_ADDRESS=0;
	  
	  //R_UART2_SEND("RESTART\r\n");
	  //for(FOR_3=1;FOR_3<=1;FOR_3++)
	  //WRITE_ADDRESS=132;
	  //ADDRESS_INC();
	  
	  while(STOP_FILE_READING==OFF)
	  {
 	  R_UART2_SEND("AT+QFREAD=");
	  for(FOR_1=1;FOR_1<=6;FOR_1++){R_UART2_SEND_User(FTP_ADDRESS[FOR_1]);NOP();}
	  R_UART2_SEND(",256\r\n");
	  ACK_RX(500,10,1,1);
	  if(RESTART==ON){RESTART=OFF;FILE_CLOSE();goto SKIP;}
	  EEPROM_FILE_WRITE();
	  }
	  FILE_CLOSE();	  
	  WRITE_ADDRESS_LSB=WRITE_ADDRESS%256;NOP();
	  WRITE_ADDRESS_MSB=WRITE_ADDRESS/256;NOP();
	  //i2c_writen(0xA0,WRITE_ADDRESS_MSB,WRITE_ADDRESS_LSB,0x04);	// END OF TRANSMISSION
	  STOP_FILE_READING=OFF;
	  //EEPROM_FILE_READ();
	  DATA_HEADER=0x0FF;
	  FIRMWARE_UPDATE=OFF;
	  //i2c_writen(0xA0,0XFF,0X02,0X23);MS_TIMER(10);
	  //i2c_writen(0xA0,0XFF,0X02,0X23);MS_TIMER(10);
	  //i2c_writen(0xA0,0XFF,0X02,0X23);MS_TIMER(10);
	  //i2c_writen(0xA0,0XFF,0X01,FRM_VERSION);MS_TIMER(10);
	  //i2c_writen(0xA0,0XFF,0X01,FRM_VERSION);MS_TIMER(10);
	  //i2c_writen(0xA0,0XFF,0X01,FRM_VERSION);MS_TIMER(10);
	  /*CURRENT_FRM_VERSION=i2c_readn(0xA0,0XFF,0X01);MS_TIMER(5);
	  R_UART2_SEND("C Version NumBer:-");
	  R_UART2_SEND_User((CURRENT_FRM_VERSION/100)+0x30);MS_TIMER(5);
	  VERSION_TEMP=CURRENT_FRM_VERSION%100;
	  R_UART2_SEND_User((VERSION_TEMP/10)+0x30);MS_TIMER(5);
	  R_UART2_SEND_User((VERSION_TEMP%10)+0x30);MS_TIMER(5);
	  R_UART2_SEND("\r\n");*/
	  
	  MS_TIMER(20);
	  FIRMWARE_UPDATE=OFF;
	  WATCH_DOG=NONE;
	  WATCH_DOG_FORCE_KILL=ON;
	  MS_TIMER(10000);
	  

SKIP:
NOP();
}

